### PR TITLE
ref: Move useColorMap outside of the individual model

### LINKED ISSUE #137: Allow for greyscale transfer function to be in-sync when using multiple channels
See [this issue](https://github.com/brown-ccv/microscopy-viewer/issues/12)

### PR DESCRIPTION
**Pull request by RobertGemmaJr**
`useColorMap` is now a prop of the component and not the individual models. Every model becomes grayscale when `!useColorMap`. Added a checkbox in the controls and handle them in state

- closes #137

### CODE REVIEW

**Comment by kmilo9999** [comment]
@RobertGemmaJr  Can you place the "Use Color Map" checkbox at the top of the options tab? It could be hard to know that the option exists.

User case: When the  "Use Color Map"  is unchecked, then modify the clip planes, and then click on the `reset` button. The datasets is color mapped, but the "Use Color Map" is still unchecked.

**Review by kmilo9999 — CHANGES_REQUESTED** [review]
@RobertGemmaJr Can you place the "Use Color Map" checkbox at the top of the options tab? It could be hard to know that the option exists.

User case: When the "Use Color Map" is unchecked, then modify the clip planes, and then click on the reset button. The datasets is color mapped, but the "Use Color Map" is still unchecked.

**Comment by RobertGemmaJr** [comment]
> Can you place the "Use Color Map" checkbox at the top of the options tab? It could be hard to know that the option exists.

The only issue is differentiating which controls are for an individual model (color map, transfer function) and which are for the whole volume (useColorMap and the sliders). I could flip them so the "global" controls are on top?

> User case: When the "Use Color Map" is unchecked, then modify the clip planes, and then click on the reset button. The datasets is color mapped, but the "Use Color Map" is still unchecked.

Looks like this is a bug, I'll fix it in a second

**Review by kmilo9999 — CHANGES_REQUESTED** [review]
I see your point. Let's leave the check box on the place you proposed it. Why dont we change the logic on that ? Rename the label to "**Use gray scale color map**" and is  `unchecked` by default. When the user checks the box, then grayscale color map is applied.

User case: I just added a control point to the transfer function and if I click on the reset button, the point remains. I thought it was a cache problem, but I also tested it on a new chrome session and the button is still there. I think is better to fix this problem asap and dont wait for a new PR.

**Comment by RobertGemmaJr** [comment]
> Rename the label to "**Use gray scale color map**" and is `unchecked` by default. When the user checks the box, then grayscale color map is applied.

We talked about what to do a fair bit at the GSDC meeting today. I'm not sure this logic really make sense, isn't grayscale literally the absence of color?

> User case: I just added a control point to the transfer function and if I click on the reset button, the point remains.

I haven't been able to recreate this problem? Whatever is added to the transfer function from the controls disappears when the reset button is clicked

**Comment by RobertGemmaJr** [comment]
@kmilo9999 @mirestrepo @eldu I've made a different version (#144) where the global controls sit on top of the others. Let me know what you think. Just looking at the layout for right now, I can clean up the style of 144 if that's preferred

**Comment by kmilo9999** [comment]
> We talked about what to do a fair bit at the GSDC meeting today. I'm not sure this logic really make sense, isn't grayscale literally the absence of color?

Well, the absence of color is black. The data itself produce a grayscale image ( or volume ). We map the data value to a RGB color located in the texture. My opinion is that "color mapping" is a technical concept.  The users that have seen the app ( at least Rachel and Jeff ) talk more about grayscale that color maps. You can make the argument that the title on the tabs says "Color Map", thus makes sense to call the checkbox "Use color map".  What do you think?

> > User case: I just added a control point to the transfer function and if I click on the reset button, the point remains.
> 
> I haven't been able to recreate this problem? Whatever is added to the transfer function from the controls disappears when the reset button is clicked

You are right, I didnt notice you have a pre-defined transfer function burnt in the example app.

**Comment by RobertGemmaJr** [comment]
Closing as stale

**Pull request closed without merging**
